version: "3.9"

services:
  dataset-creator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset_creator
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: [ "bash", "fetch-build-train.sh" ]

volumes:
  artifacts:
